### PR TITLE
New Checkout page

### PR DESCRIPTION
**Pull request by menacingsoul**
new checkout page layout and design that prevents overflowing and maintains responsiveness
efficiently 
image
image

### CODE REVIEW

**Comment by menacingsoul** [comment]
@shubham21155102 @soustab10

**Comment by shubham21155102** [comment]
@menacingsoul 
Bro use the updated qr 
As we have updated new one 
Also show qr and hide qr keep the current one

**Comment by menacingsoul** [comment]
> @menacingsoul Bro use the updated qr As we have updated new one Also show qr and hide qr keep the current one

added and updated the QR  @shubham21155102

**Comment by shubham21155102** [comment]
@menacingsoul 
Position sticky 
And Overflow in y ?

**Comment by menacingsoul** [comment]
image

**Comment by shubham21155102** [comment]
> image
> 

Ok 
I am out of campus now 
Will  merge immediately after reaching campus

**Comment by shubham21155102** [comment]
> > @menacingsoul 
> > Position sticky 
> > And Overflow in y ?
> 
> Everything is working fine in all screen sizes 

Ooh nice nice

**Pull request merged**
