### PR TITLE
Create Razorpay.ejs

### PR DESCRIPTION
**Pull request by AAKASHBANSAL96**
Best payment gateway which provides a wide range of payment methods in India.

[Demo](https://razorpay.com/docs/build/browser/assets/images/pg-demo.gif)

### CODE REVIEW

**Comment by shubham21155102** [comment]
onboarding is not happening on Razor pay so how do we use that

**Comment by AAKASHBANSAL96** [comment]
> onboarding is not happening on Razor pay so how do we use that @AAKASHBANSAL96

Yes, as per RBI guidelines they required to obtain a final payment aggregate licence, till then we can use stripe to accept payments. 

I will add strip for this.

**Comment by shubham21155102** [comment]
@AAKASHBANSAL96
So add the stripe pg
Also create a demo how you are adding stripe pg

**Comment by AAKASHBANSAL96** [comment]
> @AAKASHBANSAL96 So add the stripe pg Also create a demo how you are adding stripe pg

Sure

**Pull request closed without merging**
